export default {
  searchIcon: require('../assets/icons/search.png'),
  menuIcon: require('../assets/icons/menu.png'),
  cameraIcon: require('../assets/icons/camera.png'),
  callIcon: require('../assets/icons/call.png'),
  videoCallIcon: require('../assets/icons/videoCall.png'),
  callPlusIcon: require('../assets/icons/callPlus.png'),
  editPenIcon: require('../assets/icons/editPen.png'),
  messageIcon: require('../assets/icons/message.png'),
  backArrowIcon: require('../assets/icons/backArrow.png'),
  emojiIcon: require('../assets/icons/emoji.png'),
  linkIcon: require('../assets/icons/link.png'),
  micIcon: require('../assets/icons/mic.png'),
  heartIcon:require('../assets/icons/heartIcon.png'),
  chat:require('../assets/icons/chat.jpeg'),
  community:require('../assets/icons/community.jpeg'),
  status:require('../assets/icons/status.jpeg'),
  send:require('../assets/icons/send.png'),
  
   gallery: require('../assets/icons/gallery.png'),
  camera: require('../assets/icons/camera.png'),
  location: require('../assets/icons/location.png'),
  contact: require('../assets/icons/contact.png'),
  document: require('../assets/icons/document.png'),
};