export default {
  // communityimg: require('../assets/images/communityimg.png'),
  // user: require('../assets/images/user.png'),
  // user1: require('../assets/images/user1.jpeg'),
  // user2: require('../assets/images/user2.jpg'),
  // user3: require('../assets/images/user3.jpeg'),
  // user4: require('../assets/images/user4.jpeg'),
  // user5: require('../assets/images/user5.jpg'), 
  // user6: require('../assets/images/user6.jpeg'),
  // user7: require('../assets/images/user7.jpeg'), 
  // user8: require('../assets/images/user8.jpeg'), 
  // user9: require('../assets/images/user9.jpeg'), 
  // geo: require('../assets/images/geo.jpg'), 
  // sun: require('../assets/images/sun.png'), 
  // cartoon: require('../assets/images/cartoon.png'), 
  // whatsup: require('../assets/images/whatsup.png'), 


   communityimg1: require('../assets/images/communityimg1.jpg'),
  communityimg2: require('../assets/images/communityimg2.jpg'),
  user: require('../assets/images/user.png'),
  user1: require('../assets/images/user1.jpeg'),
  user2: require('../assets/images/user2.jpg'),
  user3: require('../assets/images/user3.jpeg'),
  user4: require('../assets/images/user4.jpeg'),
  user5: require('../assets/images/user5.jpg'), 
  user6: require('../assets/images/user6.jpeg'),
  user7: require('../assets/images/user7.jpeg'), 
  user8: require('../assets/images/user8.jpeg'), 
  user9: require('../assets/images/user9.jpeg'), 
  geo: require('../assets/images/geo.jpg'), 
  sun: require('../assets/images/sun.png'), 
  cartoon: require('../assets/images/cartoon.png'), 
  whatsup: require('../assets/images/whatsup.png'), 
};